In [1]:
#Import dependencies and file path.
import pandas as pd
file = "vine_table.csv"

In [2]:
#Read the csv file.
file_csv = pd.read_csv(file)

In [3]:
#Convert the csv file to a data frame.
vine_df = pd.DataFrame(file_csv)
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,R3VR960AHLFKDV,4,0,0,N,Y
1,R16LGVMFKIUT0G,5,0,0,N,Y
2,R1AIMEEPYHMOE4,5,1,1,N,Y
3,R1892CCSZWZ9SR,3,0,0,N,Y
4,R285P679YWVKD1,3,0,0,N,N
...,...,...,...,...,...,...
792108,R1F7BNIK2R72ZC,5,21,21,N,N
792109,RVR3U3QA0D95B,5,10,11,N,N
792110,R1X5JB9UJRZW31,5,3,5,N,N
792111,R235PHRTF7BFK7,4,5,5,N,N
792112,RZ0Y9U30658TB,5,5,6,N,N